import { legalStages } from './stages'
import { sortedCharacters } from './characters'
import { moves } from './moves'
import { actionStates } from './actionStates'
import { deathDirections } from './deathDirections'
import { sortOptions } from '../models/methods/sort'

export const filtersConfig = [
  {
    id: 'files',
    label: 'Game Filter',
    options: [
      {
        name: 'Stage',
        id: 'stage',
        type: 'multiDropdown',
        options: legalStages,
        default: [],
      },
      {
        name: 'Char 1',
        id: 'char1',
        type: 'multiDropdown',
        options: sortedCharacters,
        default: [],
      },
      {
        name: 'Char 2',
        id: 'char2',
        type: 'multiDropdown',
        options: sortedCharacters,
        default: [],
      },
      {
        name: 'Player 1',
        id: 'player1',
        type: 'textInput',
        default: [],
        autocomplete: 'names',
      },
      {
        name: 'Player 2',
        id: 'player2',
        type: 'textInput',
        default: [],
        autocomplete: 'names',
      },
    ],
  },
  {
    id: 'slpParser',
    label: 'Combo Parser',
    options: [
      {
        name: 'Min Hits',
        id: 'minHits',
        type: 'int',
        default: '2',
      },
      {
        name: 'Max Hits',
        id: 'maxHits',
        type: 'int',
        default: '',
      },
      {
        name: 'Max Files',
        id: 'maxFiles',
        type: 'int',
        default: '',
      },
      {
        name: 'Comboer Char',
        id: 'comboerChar',
        type: 'multiDropdown',
        options: sortedCharacters,
        default: [],
      },
      {
        name: 'Comboee Char',
        id: 'comboeeChar',
        type: 'multiDropdown',
        options: sortedCharacters,
        default: [],
      },
      {
        name: 'Comboer Tag',
        id: 'comboerTag',
        type: 'textInput',
        default: [],
        autocomplete: 'names',
      },
      {
        name: 'Comboee Tag',
        id: 'comboeeTag',
        type: 'textInput',
        default: [],
        autocomplete: 'names',
      },
      {
        name: 'Did Kill',
        id: 'didKill',
        type: 'checkbox',
        default: false,
      },
    ],
  },
  {
    id: 'comboFilter',
    label: 'Combo Filter',
    options: [
      {
        name: 'Min Hits',
        id: 'minHits',
        type: 'int',
        default: '3',
      },
      {
        name: 'Max Hits',
        id: 'maxHits',
        type: 'int',
        default: '',
      },
      {
        name: 'Min Damage',
        id: 'minDamage',
        type: 'int',
        default: '',
      },
      {
        name: 'Comboer Char',
        id: 'comboerChar',
        type: 'multiDropdown',
        options: sortedCharacters,
        default: [],
      },
      {
        name: 'Comboee Char',
        id: 'comboeeChar',
        type: 'multiDropdown',
        options: sortedCharacters,
        default: [],
      },
      {
        name: 'Comboer Tag',
        id: 'comboerTag',
        type: 'textInput',
        default: [],
        autocomplete: 'names',
      },
      {
        name: 'Comboee Tag',
        id: 'comboeeTag',
        type: 'textInput',
        default: [],
        autocomplete: 'names',
      },
      {
        name: 'Stage',
        id: 'comboStage',
        type: 'multiDropdown',
        options: legalStages,
        default: [],
      },
      {
        name: 'Did Kill',
        id: 'didKill',
        type: 'checkbox',
        default: true,
      },
      {
        name: 'Count Pummels',
        id: 'countPummels',
        type: 'checkbox',
        default: false,
      },
      {
        name: 'Nth Moves',
        id: 'nthMoves',
        type: 'nthMoves',
        options: moves,
        default: [],
        moves: [],
      },
    ],
  },
  {
    id: 'actionStateFilter',
    label: 'Action State',
    options: [
      {
        name: 'Start Frame',
        id: 'startFrom',
        type: 'int',
        default: '',
        placeholder: 'Clip start',
        tooltip: 'Frame offset to begin searching from. Positive = from clip start, negative = from clip end. Empty = start from first frame.',
      },
      {
        name: 'Search Range',
        id: 'searchRange',
        type: 'int',
        default: '',
        placeholder: 'All frames',
        tooltip: 'Number of frames to search. Positive = forward, negative = backward. 0 or empty = search all remaining frames.',
      },
      {
        name: 'Nth Move',
        id: 'startFromNthMove',
        type: 'positionDropdown',
        default: '',
        requiresParser: true,
        tooltip: 'Start searching from this move\'s frame. Overrides Start Frame.',
      },
      {
        name: 'Offset',
        id: 'offset',
        type: 'int',
        default: '',
        tooltip: 'Shift the start frame by +/- this many frames before searching.',
      },
      {
        name: 'Comboer State',
        id: 'comboerActionState',
        type: 'multiDropdown',
        options: actionStates,
        default: [],
        tooltip: 'Filter clips by the attacker\'s action state during the search window. Without a parser, matches any player.',
      },
      {
        name: 'Comboee State',
        id: 'comboeeActionState',
        type: 'multiDropdown',
        options: actionStates,
        default: [],
        tooltip: 'Filter clips by the defender\'s action state during the search window. Without a parser, matches any player.',
      },
      {
        name: 'Comboer Custom IDs',
        id: 'comboerCustomIds',
        type: 'textInput',
        default: '',
        tooltip: 'Comma-separated action state IDs for the Custom option (e.g. 43,44,45).',
        showWhenCustomField: 'comboerActionState',
      },
      {
        name: 'Comboee Custom IDs',
        id: 'comboeeCustomIds',
        type: 'textInput',
        default: '',
        tooltip: 'Comma-separated action state IDs for the Custom option (e.g. 43,44,45).',
        showWhenCustomField: 'comboeeActionState',
      },
      {
        name: 'Exclude',
        id: 'exclude',
        type: 'checkbox',
        default: false,
        tooltip: 'Invert the filter — keep clips where the action state was NOT found.',
      },
      {
        name: 'Comboer Min X',
        id: 'comboerMinX',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Minimum X position for the comboer. Empty = no constraint.',
      },
      {
        name: 'Comboer Max X',
        id: 'comboerMaxX',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Maximum X position for the comboer. Empty = no constraint.',
      },
      {
        name: 'Comboer Min Y',
        id: 'comboerMinY',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Minimum Y position for the comboer. Empty = no constraint.',
      },
      {
        name: 'Comboer Max Y',
        id: 'comboerMaxY',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Maximum Y position for the comboer. Empty = no constraint.',
      },
      {
        name: 'Comboee Min X',
        id: 'comboeeMinX',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Minimum X position for the comboee. Empty = no constraint.',
      },
      {
        name: 'Comboee Max X',
        id: 'comboeeMaxX',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Maximum X position for the comboee. Empty = no constraint.',
      },
      {
        name: 'Comboee Min Y',
        id: 'comboeeMinY',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Minimum Y position for the comboee. Empty = no constraint.',
      },
      {
        name: 'Comboee Max Y',
        id: 'comboeeMaxY',
        type: 'int',
        default: '',
        group: 'position',
        tooltip: 'Maximum Y position for the comboee. Empty = no constraint.',
      },
    ],
  },
  {
    id: 'reverse',
    label: 'Reverse Hit',
    options: [
      {
        name: 'Nth Move',
        id: 'n',
        type: 'positionDropdown',
        default: '',
      },
    ],
  },
  {
    id: 'sort',
    label: 'Sort',
    options: [
      {
        name: 'Sort Function',
        id: 'sortFunction',
        type: 'dropdown',
        options: sortOptions,
        default: 'dps',
      },
      {
        name: 'Reverse',
        id: 'reverse',
        type: 'checkbox',
        default: false,
      },
    ],
  },
  {
    id: 'removeStarKOFrames',
    label: 'Cut Star KO',
    options: [
      {
        name: 'Max Files',
        id: 'maxFiles',
        type: 'int',
        default: '',
      },
    ],
  },
  {
    id: 'custom',
    label: 'Custom Code',
    options: [
      {
        name: 'N',
        id: 'n',
        type: 'int',
        default: '',
      },
      {
        name: 'X',
        id: 'x',
        type: 'int',
        default: '',
      },
      {
        name: 'Y',
        id: 'y',
        type: 'int',
        default: '',
      },
      {
        name: 'Max Files',
        id: 'maxFiles',
        type: 'int',
        default: '',
      },
    ],
  },
  {
    id: 'koDirection',
    label: 'KO Direction',
    options: [
      {
        name: 'Max Files',
        id: 'maxFiles',
        type: 'int',
        default: '',
      },
      {
        name: 'Direction',
        id: 'direction',
        type: 'dropdown',
        options: deathDirections,
        default: '',
      },
    ],
  },
  {
    id: 'edgeguard',
    label: 'Edgeguards',
    options: [
      {
        name: 'Max Files',
        id: 'maxFiles',
        type: 'int',
        default: '',
      },
    ],
  },
]

export const settingsCategories = [
  { key: 'paths', label: 'Paths' },
  { key: 'video', label: 'Video Output' },
  { key: 'rendering', label: 'Gecko Codes' },
  { key: 'performance', label: 'Performance' },
  { key: 'general', label: 'General' },
] as const

export const videoConfig = [
  // Paths
  {
    label: 'Melee .iso Path',
    default: '',
    id: 'ssbmIsoPath',
    type: 'openFile',
    category: 'paths',
  },
  {
    label: 'Dolphin Path',
    default: '',
    id: 'dolphinPath',
    type: 'openFile',
    category: 'paths',
  },
  {
    label: 'Output Directory',
    default: '',
    id: 'outputPath',
    type: 'openDirectory',
    category: 'paths',
  },
  // Video Output
  {
    label: 'Recording Resolution',
    default: 2,
    id: 'resolution',
    type: 'dropdown',
    category: 'video',
    options: [
      { label: '1x - Low Quality (fast)', value: 2 },
      { label: '1.5x', value: 3 },
      { label: '2x - Normal Quality', value: 4 },
      { label: '2.5x', value: 5 },
      { label: '3x', value: 6 },
      { label: '4x - High Quality', value: 7 },
      { label: '5x', value: 8 },
      { label: '6x - Very High Quality', value: 9 },
      { label: '7x', value: 10 },
      { label: '8x - Too High Quality', value: 11 },
    ],
  },
  {
    label: 'Player Resolution',
    default: 2,
    id: 'playbackResolution',
    type: 'dropdown',
    category: 'video',
    options: [
      { label: '1x - Low Quality (fast)', value: 2 },
      { label: '1.5x', value: 3 },
      { label: '2x - Normal Quality', value: 4 },
      { label: '2.5x', value: 5 },
      { label: '3x', value: 6 },
      { label: '4x - High Quality', value: 7 },
      { label: '5x', value: 8 },
      { label: '6x - Very High Quality', value: 9 },
      { label: '7x', value: 10 },
      { label: '8x - Too High Quality', value: 11 },
    ],
  },
  {
    label: 'Bitrate (kbps)',
    default: 15000,
    id: 'bitrateKbps',
    type: 'textInput',
    category: 'video',
  },
  {
    label: 'Add Start Frames',
    default: 0,
    id: 'addStartFrames',
    type: 'int',
    category: 'video',
  },
  {
    label: 'Add End Frames',
    default: 0,
    id: 'addEndFrames',
    type: 'int',
    category: 'video',
  },
  {
    label: 'Final End Frames',
    default: 0,
    id: 'lastClipOffset',
    type: 'int',
    category: 'video',
  },
  {
    label: 'Concatenate Output',
    default: false,
    id: 'concatenate',
    type: 'checkbox',
    category: 'video',
  },
  {
    label: 'Convert to MP4',
    default: false,
    id: 'convertToMp4',
    type: 'checkbox',
    category: 'video',
  },
  // Rendering
  {
    label: 'Hide HUD',
    default: false,
    id: 'hideHud',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'Fixed Camera',
    default: false,
    id: 'fixedCamera',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'No Screen Shake',
    default: false,
    id: 'disableScreenShake',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'No Magnifying Glass',
    default: false,
    id: 'disableMagnifyingGlass',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'Hide Tags',
    default: false,
    id: 'hideTags',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'Hide Netplay Names',
    default: false,
    id: 'hideNames',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'Game Music',
    default: false,
    id: 'gameMusic',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'Enable Chants',
    default: false,
    id: 'enableChants',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'No Electric SFX',
    default: false,
    id: 'noElectricSFX',
    type: 'checkbox',
    category: 'rendering',
  },
  {
    label: 'No Crowd Noise',
    default: false,
    id: 'noCrowdNoise',
    type: 'checkbox',
    category: 'rendering',
  },
  // Performance
  {
    label: 'Dolphin Instances',
    default: 1,
    id: 'numCPUs',
    type: 'int',
    category: 'performance',
  },
  {
    label: 'Clips per Batch',
    default: 1,
    id: 'slice',
    type: 'int',
    category: 'performance',
  },
  {
    label: 'CPU Threads',
    default: 1,
    id: 'numFilterThreads',
    type: 'int',
    category: 'performance',
  },
  // General
  {
    label: 'Shuffle',
    default: false,
    id: 'shuffle',
    type: 'checkbox',
    category: 'general',
  },
  {
    label: 'Detect Duplicates on Import',
    default: false,
    id: 'detectDuplicatesOnImport',
    type: 'checkbox',
    category: 'general',
    warning: 'Can significantly slow down imports with large file counts',
  },
  {
    label: 'Warn on Parser Delete',
    default: true,
    id: 'warnOnParserDelete',
    type: 'checkbox',
    category: 'general',
  },
  {
    label: 'Advanced Mode',
    default: false,
    id: 'advancedMode',
    type: 'checkbox',
    category: 'general',
  },
  {
    label: 'Test Mode',
    default: false,
    id: 'testMode',
    type: 'checkbox',
    category: 'general',
  },
  {
    label: 'Test Dolphin',
    id: 'testDolphin',
    type: 'button',
    category: 'general',
    buttonLabel: 'Launch Test',
  },
]
