export const config = {
  lastArchivePath: '',
  hideHud: false,
  gameMusic: false,
  enableChants: false,
  disableScreenShake: false,
  hideTags: false,
  hideNames: false,
  overlaySource: false,
  fixedCamera: false,
  noElectricSFX: false,
  noCrowdNoise: false,
  disableMagnifyingGlass: false,
  shuffle: false,
  resolution: '1x',
  bitrateKbps: 15000,
  addStartFrames: 0,
  addEndFrames: 0,
  lastClipOffset: 1,
  numCPUs: 1,
  slice: 0,
  dolphinCutoff: 300,
  ssbmIsoPath: '',
  dolphinPath: '',
  outputPath: '',
}

export const archive = {
  files: [],
  filters: [],
  path: '',
  name: 'default_archive',
  createdAt: 1006329600,
  updatedAt: 1006329600,
}
