export const config = {
  lastArchivePath: '',
  projectName: '',
  hideHud: false,
  gameMusic: false,
  enableChants: false,
  disableScreenShake: false,
  hideTags: false,
  hideNames: false,
  overlaySource: false,
  fixedCamera: false,
  noElectricSFX: false,
  noCrowdNoise: false,
  disableMagnifyingGlass: false,
  shuffle: false,
  resolution: '1x',
  bitrateKbps: 15000,
  addStartFrames: 0,
  addEndFrames: 0,
  lastClipOffset: 1,
  numCPUs: 1,
  numFilterThreads: 1,
  slice: 2,
  dolphinCutoff: 300,
  ssbmIsoPath: '',
  dolphinPath: '',
  outputPath: '',
}

export const archive = {
  path: '',
  name: 'default_lm_project',
  createdAt: 1006329600,
  files: 0,
  filters: [
    // {
    //   id: 'filter_0',
    //   label: 'Game Filter',
    //   type: 'files',
    //   isProcessed: false,
    //   results: 0,
    //   params: {
    //     stage: '',
    //     char1: '',
    //     char2: '',
    //     player1: '',
    //     player2: '',
    //   }
    // },
    // {
    //   id: 'filter_1',
    //   label: 'Combo Parser',
    //   type: 'slpParser',
    //   isProcessed: false,
    //   params: {
    //     minHits: '2',
    //     maxHits: '',
    //     maxFiles: '100',
    //     comboerChar: '',
    //     comboeeChar: '',
    //     comboerTag: '',
    //     comboeeTag: '',
    //     didKill: true,
    //   },
    //   results: 0,
    // },
    // {
    //   label: 'Combo Filter',
    //   type: 'comboFilter',
    //   isProcessed: false,
    //   params: {
    //     minHits: '4',
    //     maxHits: '',
    //     minDamage: '',
    //     comboerChar: '',
    //     comboeeChar: '',
    //     comboerTag: '',
    //     comboeeTag: '',
    //     comboStage: '',
    //     didKill: true,
    //     excludeICs: false,
    //     nthMoves: [],
    //   },
    //   results: [],
    // },
  ],
}
