export const legalStages = [
  {
    id: 2,
    name: 'Fountain of Dreams',
    shortName: 'Fountain',
    tag: 'fod',
  },
  {
    id: 3,
    name: 'Pokémon Stadium',
    shortName: 'Pokemon',
    tag: 'ps',
  },
  {
    id: 8,
    name: "Yoshi's Story",
    shortName: "Yoshi's",
    tag: 'ys',
  },
  {
    id: 28,
    name: 'Dream Land',
    shortName: 'Dreamland',
    tag: 'dl',
  },
  {
    id: 31,
    name: 'Battlefield',
    shortName: 'BattleField',
    tag: 'bf',
  },
  {
    id: 32,
    name: 'Final Destination',
    shortName: 'FD',
    tag: 'fd',
  },
]

export const stages = {
  2: {
    id: 2,
    name: 'Fountain of Dreams',
    img: 'stages/fountain.jpg',
    tag: 'fod',
  },
  3: {
    id: 3,
    name: 'Pokémon Stadium',
    img: 'stages/stadium.jpg',
    tag: 'ps',
  },
  4: {
    id: 4,
    name: "Princess Peach's Castle",
    img: 'stages/nonlegal.jpg',
    tag: 'pc',
  },
  5: {
    id: 5,
    name: 'Kongo Jungle',
    img: 'stages/nonlegal.jpg',
    tag: 'kj',
  },
  6: {
    id: 6,
    name: 'Brinstar',
    img: 'stages/nonlegal.jpg',
    tag: 'bs',
  },
  7: {
    id: 7,
    name: 'Corneria',
    img: 'stages/nonlegal.jpg',
    tag: 'cr',
  },
  8: {
    id: 8,
    name: "Yoshi's Story",
    img: 'stages/yoshis.jpg',
    tag: 'ys',
  },
  9: {
    id: 9,
    name: 'Onett',
    img: 'stages/nonlegal.jpg',
    tag: 'on',
  },
  10: {
    id: 10,
    name: 'Mute City',
    img: 'stages/nonlegal.jpg',
    tag: 'mc',
  },
  11: {
    id: 11,
    name: 'Rainbow Cruise',
    img: 'stages/nonlegal.jpg',
    tag: 'rc',
  },
  12: {
    id: 12,
    name: 'Jungle Japes',
    img: 'stages/nonlegal.jpg',
    tag: 'jj',
  },
  13: {
    id: 13,
    name: 'Great Bay',
    img: 'stages/nonlegal.jpg',
    tag: 'gb',
  },
  14: {
    id: 14,
    name: 'Hyrule Temple',
    img: 'stages/nonlegal.jpg',
    tag: 'ht',
  },
  15: {
    id: 15,
    name: 'Brinstar Depths',
    img: 'stages/nonlegal.jpg',
    tag: 'bd',
  },
  16: {
    id: 16,
    name: "Yoshi's Island'",
    img: 'stages/nonlegal.jpg',
    tag: 'yi',
  },
  17: {
    id: 17,
    name: 'Green Greens',
    img: 'stages/nonlegal.jpg',
    tag: 'gg',
  },
  18: {
    id: 18,
    name: 'Fourside',
    img: 'stages/nonlegal.jpg',
    tag: 'fs',
  },
  19: {
    id: 19,
    name: 'Mushroom Kingdom I',
    img: 'stages/nonlegal.jpg',
    tag: 'mk',
  },
  20: {
    id: 20,
    name: 'Mushroom Kingdom II',
    img: 'stages/nonlegal.jpg',
    tag: 'mk2',
  },
  22: {
    id: 22,
    name: 'Venom',
    img: 'stages/nonlegal.jpg',
    tag: 'vn',
  },
  23: {
    id: 23,
    name: 'Poké Floats',
    img: 'stages/nonlegal.jpg',
    tag: 'pf',
  },
  24: {
    id: 24,
    name: 'Big Blue',
    img: 'stages/nonlegal.jpg',
    tag: 'bb',
  },
  25: {
    id: 25,
    name: 'Icicle Mountain',
    img: 'stages/nonlegal.jpg',
    tag: 'im',
  },
  26: {
    id: 26,
    name: 'Icetop',
    img: 'stages/nonlegal.jpg',
    tag: 'it',
  },
  27: {
    id: 27,
    name: 'Flat Zone',
    img: 'stages/nonlegal.jpg',
    tag: 'fz',
  },
  28: {
    id: 28,
    name: 'Dream Land',
    img: 'stages/dreamland.jpg',
    tag: 'dl',
  },
  29: {
    id: 29,
    name: "Yoshi's Island N64",
    img: 'stages/nonlegal.jpg',
    tag: 'yi64',
  },
  30: {
    id: 30,
    name: 'Kongo Jungle N64',
    img: 'stages/nonlegal.jpg',
    tag: 'kj64',
  },
  31: {
    id: 31,
    name: 'Battlefield',
    img: 'stages/battlefield.jpg',
    tag: 'bf',
  },
  32: {
    id: 32,
    name: 'Final Destination',
    img: 'stages/finaldestination.jpg',
    tag: 'fd',
  },
}

// module.exports = { stages }
