name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature? What problem does it solve?
    validations:
      required: true
